indexPath: "/home/raha/go/src/shakhes/blocks4/1.txt"
docsNum: 100
championPath: "/home/raha/go/src/shakhes/champion.txt"
clusters:
  - path: "/home/raha/go/src/shakhes/بهداشت/blocks4/1.txt"
    size: 60
  - path: "/home/raha/go/src/shakhes/تاریخ/blocks5/1.txt"
    size: 60
  - path: "/home/raha/go/src/shakhes/ریاضیات/blocks4/1.txt"
    size: 60
  - path: "/home/raha/go/src/shakhes/فناوری/blocks4/1.txt"
    size: 60
  - path: "/home/raha/go/src/shakhes/فیزیک/blocks4/1.txt"
    size: 60